---
title: "Spain Primera 1st 19 games Player Stats"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup, include=FALSE}
library(flexdashboard)
library(data.table)
library(stringr)
library(tidyverse)
library(highcharter)
library(DT)
library(plotly)
library(tidyverse)
```

```{r load_data, include = FALSE}
dt <- fread('/Users/deano/Documents/R/flexidash/spain_exp_player_stats/exp_player_stats_spain.csv', encoding = 'Latin-1')
```

```{r functions, include = FALSE}
remove.separator <- function(x, sep){
  # remove + / - separator from vector
  result <- unlist(strsplit(x,split=sep, fixed=TRUE))
  result <- result[[1]]
  return(result)
}
```

```{r prepare data for All PLayers page, include = FALSE}
# remove + and - from xG
dt$xG <- mapply(remove.separator, dt$xG, '+')
dt$xG <- mapply(remove.separator, dt$xG, '-')

# remove + and - from xA
dt$xA <- mapply(remove.separator, dt$xA, '+')
dt$xA <- mapply(remove.separator, dt$xA, '-')

dt$xG <- as.numeric(dt$xG)
dt$xA <- as.numeric(dt$xA)

# add G90
dt$G90 <- (dt$G / dt$Min) * 90
dt$G90 <- round(dt$G90, 2)

# add diff.GxG
dt$diff.GxG <- dt$G - dt$xG
dt$diff.GxG <- round(dt$diff.GxG, 2)
```

```{r prepare data for Teams page, include = FALSE}
barca <- dt[team=='Barcelona',]
atletico <- dt[team=='Atletico',]
sevilla <- dt[team=='Sevilla',]
```


All Players
=====================================


### 

```{r}
datatable(
  dt, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  ))
```


Team Goals By Player
=====================================

Row {.tabset .tabset-fade}
-------------------------------------
   
### Barcelona

```{r}
barca %>%
  hchart(type = "treemap", hcaes(x = Player, value = G, color = G)) 
```   
 
### Atletico
    
```{r}
atletico %>%
  hchart(type = "treemap", hcaes(x = Player, value = G, color = G)) 
```

### Sevilla
    
```{r}
sevilla %>%
  hchart(type = "treemap", hcaes(x = Player, value = G, color = G)) 
```